[package]
name = "quant"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "quant"


[dependencies]
rand="0.8.4"
serde= { version = "1.0.130", features = ["derive"] }
serde_json="1.0.71"
anyhow={version="1.0.48",feature = "std"}
futures="0.3.18"
libc="0.2.109"