package currencyutil

const (
	CurrencyAED string = "aed" // United Arab Emirates Dirham
	CurrencyAFN string = "afn" // Afghan Afghani
	CurrencyALL string = "all" // Albanian Lek
	CurrencyAMD string = "amd" // Armenian Dram
	CurrencyANG string = "ang" // Netherlands Antillean Gulden
	CurrencyAOA string = "aoa" // Angolan Kwanza
	CurrencyARS string = "ars" // Argentine Peso
	CurrencyAUD string = "aud" // Australian Dollar
	CurrencyAWG string = "awg" // Aruban Florin
	CurrencyAZN string = "azn" // Azerbaijani Manat
	CurrencyBAM string = "bam" // Bosnia & Herzegovina Convertible Mark
	CurrencyBBD string = "bbd" // Barbadian Dollar
	CurrencyBDT string = "bdt" // Bangladeshi Taka
	CurrencyBGN string = "bgn" // Bulgarian Lev
	CurrencyBIF string = "bif" // Burundian Franc
	CurrencyBMD string = "bmd" // Bermudian Dollar
	CurrencyBND string = "bnd" // Brunei Dollar
	CurrencyBOB string = "bob" // Bolivian Boliviano
	CurrencyBRL string = "brl" // Brazilian Real
	CurrencyBSD string = "bsd" // Bahamian Dollar
	CurrencyBWP string = "bwp" // Botswana Pula
	CurrencyBZD string = "bzd" // Belize Dollar
	CurrencyCAD string = "cad" // Canadian Dollar
	CurrencyCDF string = "cdf" // Congolese Franc
	CurrencyCHF string = "chf" // Swiss Franc
	CurrencyCLP string = "clp" // Chilean Peso
	CurrencyCNY string = "cny" // Chinese Renminbi Yuan
	CurrencyCOP string = "cop" // Colombian Peso
	CurrencyCRC string = "crc" // Costa Rican Colón
	CurrencyCVE string = "cve" // Cape Verdean Escudo
	CurrencyCZK string = "czk" // Czech Koruna
	CurrencyDJF string = "djf" // Djiboutian Franc
	CurrencyDKK string = "dkk" // Danish Krone
	CurrencyDOP string = "dop" // Dominican Peso
	CurrencyDZD string = "dzd" // Algerian Dinar
	CurrencyEEK string = "eek" // Estonian Kroon
	CurrencyEGP string = "egp" // Egyptian Pound
	CurrencyETB string = "etb" // Ethiopian Birr
	CurrencyEUR string = "eur" // Euro
	CurrencyFJD string = "fjd" // Fijian Dollar
	CurrencyFKP string = "fkp" // Falkland Islands Pound
	CurrencyGBP string = "gbp" // British Pound
	CurrencyGEL string = "gel" // Georgian Lari
	CurrencyGIP string = "gip" // Gibraltar Pound
	CurrencyGMD string = "gmd" // Gambian Dalasi
	CurrencyGNF string = "gnf" // Guinean Franc
	CurrencyGTQ string = "gtq" // Guatemalan Quetzal
	CurrencyGYD string = "gyd" // Guyanese Dollar
	CurrencyHKD string = "hkd" // Hong Kong Dollar
	CurrencyHNL string = "hnl" // Honduran Lempira
	CurrencyHRK string = "hrk" // Croatian Kuna
	CurrencyHTG string = "htg" // Haitian Gourde
	CurrencyHUF string = "huf" // Hungarian Forint
	CurrencyIDR string = "idr" // Indonesian Rupiah
	CurrencyILS string = "ils" // Israeli New Sheqel
	CurrencyINR string = "inr" // Indian Rupee
	CurrencyISK string = "isk" // Icelandic Króna
	CurrencyJMD string = "jmd" // Jamaican Dollar
	CurrencyJPY string = "jpy" // Japanese Yen
	CurrencyKES string = "kes" // Kenyan Shilling
	CurrencyKGS string = "kgs" // Kyrgyzstani Som
	CurrencyKHR string = "khr" // Cambodian Riel
	CurrencyKMF string = "kmf" // Comorian Franc
	CurrencyKRW string = "krw" // South Korean Won
	CurrencyKYD string = "kyd" // Cayman Islands Dollar
	CurrencyKZT string = "kzt" // Kazakhstani Tenge
	CurrencyLAK string = "lak" // Lao Kip
	CurrencyLBP string = "lbp" // Lebanese Pound
	CurrencyLKR string = "lkr" // Sri Lankan Rupee
	CurrencyLRD string = "lrd" // Liberian Dollar
	CurrencyLSL string = "lsl" // Lesotho Loti
	CurrencyLTL string = "ltl" // Lithuanian Litas
	CurrencyLVL string = "lvl" // Latvian Lats
	CurrencyMAD string = "mad" // Moroccan Dirham
	CurrencyMDL string = "mdl" // Moldovan Leu
	CurrencyMGA string = "mga" // Malagasy Ariary
	CurrencyMKD string = "mkd" // Macedonian Denar
	CurrencyMNT string = "mnt" // Mongolian Tögrög
	CurrencyMOP string = "mop" // Macanese Pataca
	CurrencyMRO string = "mro" // Mauritanian Ouguiya
	CurrencyMUR string = "mur" // Mauritian Rupee
	CurrencyMVR string = "mvr" // Maldivian Rufiyaa
	CurrencyMWK string = "mwk" // Malawian Kwacha
	CurrencyMXN string = "mxn" // Mexican Peso
	CurrencyMYR string = "myr" // Malaysian Ringgit
	CurrencyMZN string = "mzn" // Mozambican Metical
	CurrencyNAD string = "nad" // Namibian Dollar
	CurrencyNGN string = "ngn" // Nigerian Naira
	CurrencyNIO string = "nio" // Nicaraguan Córdoba
	CurrencyNOK string = "nok" // Norwegian Krone
	CurrencyNPR string = "npr" // Nepalese Rupee
	CurrencyNZD string = "nzd" // New Zealand Dollar
	CurrencyPAB string = "pab" // Panamanian Balboa
	CurrencyPEN string = "pen" // Peruvian Nuevo Sol
	CurrencyPGK string = "pgk" // Papua New Guinean Kina
	CurrencyPHP string = "php" // Philippine Peso
	CurrencyPKR string = "pkr" // Pakistani Rupee
	CurrencyPLN string = "pln" // Polish Złoty
	CurrencyPYG string = "pyg" // Paraguayan Guaraní
	CurrencyQAR string = "qar" // Qatari Riyal
	CurrencyRON string = "ron" // Romanian Leu
	CurrencyRSD string = "rsd" // Serbian Dinar
	CurrencyRUB string = "rub" // Russian Ruble
	CurrencyRWF string = "rwf" // Rwandan Franc
	CurrencySAR string = "sar" // Saudi Riyal
	CurrencySBD string = "sbd" // Solomon Islands Dollar
	CurrencySCR string = "scr" // Seychellois Rupee
	CurrencySEK string = "sek" // Swedish Krona
	CurrencySGD string = "sgd" // Singapore Dollar
	CurrencySHP string = "shp" // Saint Helenian Pound
	CurrencySLL string = "sll" // Sierra Leonean Leone
	CurrencySOS string = "sos" // Somali Shilling
	CurrencySRD string = "srd" // Surinamese Dollar
	CurrencySTD string = "std" // São Tomé and Príncipe Dobra
	CurrencySVC string = "svc" // Salvadoran Colón
	CurrencySZL string = "szl" // Swazi Lilangeni
	CurrencyTHB string = "thb" // Thai Baht
	CurrencyTJS string = "tjs" // Tajikistani Somoni
	CurrencyTOP string = "top" // Tongan Paʻanga
	CurrencyTRY string = "try" // Turkish Lira
	CurrencyTTD string = "ttd" // Trinidad and Tobago Dollar
	CurrencyTWD string = "twd" // New Taiwan Dollar
	CurrencyTZS string = "tzs" // Tanzanian Shilling
	CurrencyUAH string = "uah" // Ukrainian Hryvnia
	CurrencyUGX string = "ugx" // Ugandan Shilling
	CurrencyUSD string = "usd" // United States Dollar
	CurrencyUYU string = "uyu" // Uruguayan Peso
	CurrencyUZS string = "uzs" // Uzbekistani Som
	CurrencyVEF string = "vef" // Venezuelan Bolívar
	CurrencyVND string = "vnd" // Vietnamese Đồng
	CurrencyVUV string = "vuv" // Vanuatu Vatu
	CurrencyWST string = "wst" // Samoan Tala
	CurrencyXAF string = "xaf" // Central African Cfa Franc
	CurrencyXCD string = "xcd" // East Caribbean Dollar
	CurrencyXOF string = "xof" // West African Cfa Franc
	CurrencyXPF string = "xpf" // Cfp Franc
	CurrencyYER string = "yer" // Yemeni Rial
	CurrencyZAR string = "zar" // South African Rand
	CurrencyZMW string = "zmw" // Zambian Kwacha
)

var currMap = make(map[string]string, 144)

func init() {
	currMap[CurrencyAED] = CurrencyAED
	currMap[CurrencyAFN] = CurrencyAFN
	currMap[CurrencyALL] = CurrencyALL
	currMap[CurrencyAMD] = CurrencyAMD
	currMap[CurrencyANG] = CurrencyANG
	currMap[CurrencyAOA] = CurrencyAOA
	currMap[CurrencyARS] = CurrencyARS
	currMap[CurrencyAUD] = CurrencyAUD
	currMap[CurrencyAWG] = CurrencyAWG
	currMap[CurrencyAZN] = CurrencyAZN
	currMap[CurrencyBAM] = CurrencyBAM
	currMap[CurrencyBBD] = CurrencyBBD
	currMap[CurrencyBDT] = CurrencyBDT
	currMap[CurrencyBGN] = CurrencyBGN
	currMap[CurrencyBIF] = CurrencyBIF
	currMap[CurrencyBMD] = CurrencyBMD
	currMap[CurrencyBND] = CurrencyBND
	currMap[CurrencyBOB] = CurrencyBOB
	currMap[CurrencyBRL] = CurrencyBRL
	currMap[CurrencyBSD] = CurrencyBSD
	currMap[CurrencyBWP] = CurrencyBWP
	currMap[CurrencyBZD] = CurrencyBZD
	currMap[CurrencyCAD] = CurrencyCAD
	currMap[CurrencyCDF] = CurrencyCDF
	currMap[CurrencyCHF] = CurrencyCHF
	currMap[CurrencyCLP] = CurrencyCLP
	currMap[CurrencyCNY] = CurrencyCNY
	currMap[CurrencyCOP] = CurrencyCOP
	currMap[CurrencyCRC] = CurrencyCRC
	currMap[CurrencyCVE] = CurrencyCVE
	currMap[CurrencyCZK] = CurrencyCZK
	currMap[CurrencyDJF] = CurrencyDJF
	currMap[CurrencyDKK] = CurrencyDKK
	currMap[CurrencyDOP] = CurrencyDOP
	currMap[CurrencyDZD] = CurrencyDZD
	currMap[CurrencyEEK] = CurrencyEEK
	currMap[CurrencyEGP] = CurrencyEGP
	currMap[CurrencyETB] = CurrencyETB
	currMap[CurrencyEUR] = CurrencyEUR
	currMap[CurrencyFJD] = CurrencyFJD
	currMap[CurrencyFKP] = CurrencyFKP
	currMap[CurrencyGBP] = CurrencyGBP
	currMap[CurrencyGEL] = CurrencyGEL
	currMap[CurrencyGIP] = CurrencyGIP
	currMap[CurrencyGMD] = CurrencyGMD
	currMap[CurrencyGNF] = CurrencyGNF
	currMap[CurrencyGTQ] = CurrencyGTQ
	currMap[CurrencyGYD] = CurrencyGYD
	currMap[CurrencyHKD] = CurrencyHKD
	currMap[CurrencyHNL] = CurrencyHNL
	currMap[CurrencyHRK] = CurrencyHRK
	currMap[CurrencyHTG] = CurrencyHTG
	currMap[CurrencyHUF] = CurrencyHUF
	currMap[CurrencyIDR] = CurrencyIDR
	currMap[CurrencyILS] = CurrencyILS
	currMap[CurrencyINR] = CurrencyINR
	currMap[CurrencyISK] = CurrencyISK
	currMap[CurrencyJMD] = CurrencyJMD
	currMap[CurrencyJPY] = CurrencyJPY
	currMap[CurrencyKES] = CurrencyKES
	currMap[CurrencyKGS] = CurrencyKGS
	currMap[CurrencyKHR] = CurrencyKHR
	currMap[CurrencyKMF] = CurrencyKMF
	currMap[CurrencyKRW] = CurrencyKRW
	currMap[CurrencyKYD] = CurrencyKYD
	currMap[CurrencyKZT] = CurrencyKZT
	currMap[CurrencyLAK] = CurrencyLAK
	currMap[CurrencyLBP] = CurrencyLBP
	currMap[CurrencyLKR] = CurrencyLKR
	currMap[CurrencyLRD] = CurrencyLRD
	currMap[CurrencyLSL] = CurrencyLSL
	currMap[CurrencyLTL] = CurrencyLTL
	currMap[CurrencyLVL] = CurrencyLVL
	currMap[CurrencyMAD] = CurrencyMAD
	currMap[CurrencyMDL] = CurrencyMDL
	currMap[CurrencyMGA] = CurrencyMGA
	currMap[CurrencyMKD] = CurrencyMKD
	currMap[CurrencyMNT] = CurrencyMNT
	currMap[CurrencyMOP] = CurrencyMOP
	currMap[CurrencyMRO] = CurrencyMRO
	currMap[CurrencyMUR] = CurrencyMUR
	currMap[CurrencyMVR] = CurrencyMVR
	currMap[CurrencyMWK] = CurrencyMWK
	currMap[CurrencyMXN] = CurrencyMXN
	currMap[CurrencyMYR] = CurrencyMYR
	currMap[CurrencyMZN] = CurrencyMZN
	currMap[CurrencyNAD] = CurrencyNAD
	currMap[CurrencyNGN] = CurrencyNGN
	currMap[CurrencyNIO] = CurrencyNIO
	currMap[CurrencyNOK] = CurrencyNOK
	currMap[CurrencyNPR] = CurrencyNPR
	currMap[CurrencyNZD] = CurrencyNZD
	currMap[CurrencyPAB] = CurrencyPAB
	currMap[CurrencyPEN] = CurrencyPEN
	currMap[CurrencyPGK] = CurrencyPGK
	currMap[CurrencyPHP] = CurrencyPHP
	currMap[CurrencyPKR] = CurrencyPKR
	currMap[CurrencyPLN] = CurrencyPLN
	currMap[CurrencyPYG] = CurrencyPYG
	currMap[CurrencyQAR] = CurrencyQAR
	currMap[CurrencyRON] = CurrencyRON
	currMap[CurrencyRSD] = CurrencyRSD
	currMap[CurrencyRUB] = CurrencyRUB
	currMap[CurrencyRWF] = CurrencyRWF
	currMap[CurrencySAR] = CurrencySAR
	currMap[CurrencySBD] = CurrencySBD
	currMap[CurrencySCR] = CurrencySCR
	currMap[CurrencySEK] = CurrencySEK
	currMap[CurrencySGD] = CurrencySGD
	currMap[CurrencySHP] = CurrencySHP
	currMap[CurrencySLL] = CurrencySLL
	currMap[CurrencySOS] = CurrencySOS
	currMap[CurrencySRD] = CurrencySRD
	currMap[CurrencySTD] = CurrencySTD
	currMap[CurrencySVC] = CurrencySVC
	currMap[CurrencySZL] = CurrencySZL
	currMap[CurrencyTHB] = CurrencyTHB
	currMap[CurrencyTJS] = CurrencyTJS
	currMap[CurrencyTOP] = CurrencyTOP
	currMap[CurrencyTRY] = CurrencyTRY
	currMap[CurrencyTTD] = CurrencyTTD
	currMap[CurrencyTWD] = CurrencyTWD
	currMap[CurrencyTZS] = CurrencyTZS
	currMap[CurrencyUAH] = CurrencyUAH
	currMap[CurrencyUGX] = CurrencyUGX
	currMap[CurrencyUSD] = CurrencyUSD
	currMap[CurrencyUYU] = CurrencyUYU
	currMap[CurrencyUZS] = CurrencyUZS
	currMap[CurrencyVEF] = CurrencyVEF
	currMap[CurrencyVND] = CurrencyVND
	currMap[CurrencyVUV] = CurrencyVUV
	currMap[CurrencyWST] = CurrencyWST
	currMap[CurrencyXAF] = CurrencyXAF
	currMap[CurrencyXCD] = CurrencyXCD
	currMap[CurrencyXOF] = CurrencyXOF
	currMap[CurrencyXPF] = CurrencyXPF
	currMap[CurrencyYER] = CurrencyYER
	currMap[CurrencyZAR] = CurrencyZAR
	currMap[CurrencyZMW] = CurrencyZMW
}
